Feature uh#07 aprovisionar web
juan-bol/aik-portal-iac pull request #1
Opened 2020-04-24 16:39 UTC by juan-bol

2020-04-25 21:30 UTC, juanfe2793 requested changes

2020-04-25 21:30 UTC, juanfe2793 commented on Saltstack/states/yum-s3/files/cob.conf
> +access_key = AasdasdKIAVSBasdasdR2CZ3AFFOI3OP
Con esas llaves así de expuestas No apruebo este PR never

2020-04-28 03:58 UTC, JuanFelipeGomezTIC requested changes

2020-04-28 03:58 UTC, JuanFelipeGomezTIC commented on Saltstack/states/aik-ui/init.sls
> +    - name: https://github.com/icesi-ops/aik-portal
Esto debería apuntar a sus repos, no?

2020-04-28 03:58 UTC, JuanFelipeGomezTIC commented on terraform/main.tf
>      user_data = <<-EOF
Recomendación, utilicen esta forma: user_data = file("../scripts/jenkins.sh")

Así puedo traer el user data de otro lado y no queda la plantilla de esta manera. Es una forma más profesional

2020-04-28 03:58 UTC, JuanFelipeGomezTIC commented on terraform/main.tf
> -    sudo yum install -y git
Porque van a instalar de nuevo git?

2020-05-09 00:45 UTC, closed without merging